name: Release Snapshot to NPM

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup and Build
        uses: ./.github/actions/setup

      - name: Publish snapshot to NPM
        run: |
          # Temporarily change package name to @syvlabshq scope
          npm pkg set name="@syvlabshq/surge-periphery"
          npm version 0.0.0-snapshot.$(git rev-parse --short HEAD) --git-tag-version=false
          npm publish --no-git-checks --tag snapshot --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
