name: Release Snapshot to NPM

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Setup and Build
        uses: ./.github/actions/setup

      - name: Publish snapshot to NPM
        run: npm run release-snapshot
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
